server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.106.184.220:3306/visitor?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: tourist
    password: tourist

